spring:
  datasource:
    url: 'jdbc:h2:file:./testdb;MODE=MySQL;'
  h2:
    console:
      enabled: on
logging:
  level:
    pl.edu.wszib: DEBUG
springdoc:
  packages-to-scan: pl.edu.wszib.infrastructure.product